# Generated by Django 5.2.3 on 2026-01-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rch_number', models.CharField(max_length=20, unique=True, verbose_name='RCH Number')),
                ('parent_number', models.CharField(max_length=15, verbose_name='Parent Number')),
                ('child_name', models.CharField(max_length=100, verbose_name='Child Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Children',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vaccine Name')),
                ('recommended_age_months', models.IntegerField(verbose_name='Recommended Age (months)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'ordering': ['recommended_age_months', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('administered_date', models.DateField(blank=True, null=True, verbose_name='Administered Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='vaccine_app.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_app.vaccine')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'unique_together': {('child', 'vaccine')},
            },
        ),
    ]
